### ISSUE TITLE
Add support for showing branches

### ISSUE THREAD

**Issue by assimovt** [flowdock/jenkins-flowdock-plugin#13]
It would be great to have the inbox message include the branch name, for example:

```my-repo/my-branch build 1 was successful```

With the contents:

```
Build: 1
Branch: my-branch
Result: SUCCESS
URL: http://example.com
```

**Comment by anttipitkanen** [comment]
@Mange @kontulai @jlaiho @vluoto @assimovt : Sorry for the delay! I've added some common version control environment variables to the inbox notification, let me know if there's something missing! (preferably as an issue/PR to the new repository)
https://github.com/jenkinsci/flowdock-plugin/commit/cbe38466ff6fe38f3f52fcc09c1d677002939169

I also released version `1.1.7` of the plugin, it should be available in Jenkins update service soon.
